### ISSUE TITLE
Tracking issue for 0.21.0 release

### ISSUE THREAD

**Issue by KodrAus** [elastic-rs/elastic#319]
- [ ] #316
- [ ] #317
- [ ] #277 (needs more integration testing)
- [ ] Tidy up docs (they're probably a bit inaccurate by now)
- [ ] Check doc links
